[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files for a shorter time
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Security headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://draftstox.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Preconnect to external domains for performance
[[headers]]
  for = "/*"
  [headers.values]
    Link = '''
    <https://fonts.googleapis.com>; rel=preconnect,
    <https://fonts.gstatic.com>; rel=preconnect; crossorigin,
    <https://api.convertkit.com>; rel=preconnect,
    <https://www.alphavantage.co>; rel=preconnect,
    <https://query1.finance.yahoo.com>; rel=preconnect
    ''' 